name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ dev, main ]

jobs:
  build-and-publish-to-exchange:
    name: build-and-publish-to-exchange
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'

    steps:
      
      - name: Publish to Exchange
        run: |
          mvn -B deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

  deploy-to-cloudhub:
    name: deploy-to-cloudhub
    runs-on: ubuntu-latest
    needs: [ build-and-publish-to-exchange ]
    if: github.ref_name == 'main' || github.ref_name == 'dev'

    steps:
      
      - name: Deploy to CloudHub 2.0
        run: |
          mvn -B deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"
