name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ dev, main ]

jobs:
  build-and-publish-to-exchange:
    name: build-and-publish-to-exchange
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'

    steps:
      - name: Checkout this repo uses: actions/checkout@v4 
      - name: Cache dependencies uses: actions/cache@v4 with: path: ~/.m2/repository key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} restore-keys: ${{ runner.os }}-maven- 
      - name: Set up JDK 1.8 uses: actions/setup-java@v4 with: distribution: "zulu" java-version: 8
      - name: Publish to Exchange
        run: |
          mvn -B deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

  deploy-to-cloudhub:
    name: deploy-to-cloudhub
    runs-on: ubuntu-latest
    needs: [ build-and-publish-to-exchange ]
    if: github.ref_name == 'main' || github.ref_name == 'dev'

    steps:
      - name: Checkout this repo uses: actions/checkout@v4 
      - name: Cache dependencies uses: actions/cache@v4 with: path: ~/.m2/repository key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} restore-keys: ${{ runner.os }}-maven- 
      - name: Set up JDK 1.8 uses: actions/setup-java@v4 with: distribution: "zulu" java-version: 8
      - name: Deploy to CloudHub 2.0
        run: |
          mvn -B deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"
